### ISSUE TITLE
Getting error issuing command "brew install ocm"

### ISSUE THREAD

**Issue by garysuth** [cblecker/homebrew-tap#1]
I am trying to install ocm-cli and issued "brew install ocm" 

I received the following

==> Installing ocm from cblecker/tap
==> Cloning https://github.com/openshift-online/ocm-cli.git
Updating /Users/garycs/Library/Caches/Homebrew/ocm--git
==> Checking out tag v0.1.64
HEAD is now at 223ae5a Merge pull request #396 from vkareh/release_v0.1.64
HEAD is now at 223ae5a Merge pull request #396 from vkareh/release_v0.1.64
==> go build ./cmd/ocm
Last 15 lines from /Users/garycs/Library/Logs/Homebrew/ocm/01.go:
2022-10-20 12:16:13 -0400

go
build
-trimpath
-o
/usr/local/Cellar/ocm/0.1.64/bin/ocm
./cmd/ocm

pkg/output/table.go:24:2: package embed is not in GOROOT (/usr/local/Cellar/go/1.15.7_1/libexec/src/embed)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/cblecker/homebrew-tap/issues

Can you please help?

**Comment by cblecker** [comment]
You're using an older version of go. Please try to `brew update` and `brew upgrade` and then retry.
